repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: ['--remove-all-unused-imports', '--remove-unused-variables', '--in-place', '--recursive']
